### ISSUE TITLE
SecurityGate does not work as expected

### ISSUE THREAD

**Issue by kferkic** [iabudiab/dependency-track-maven-plugin#5]
The `securityGate` config is a bit confusing.

With the following configuration:
```xml
<securityGate>
  <critical>0</critical>
  <high>0</high>
  <medium>0</medium>
  <low>0</low>
</securityGate>
```
the build will fail - even if the project has no vulnerabilities.
This is because `SecurityGate.applyOn` checks if the number of found issues for the given severity is greater **or equal** to the configured threshold.

```java
public void applyOn(ProjectMetrics projectMetrics) throws SecurityGateRejectionException {
	if (projectMetrics.getCritical() >= critical || //
			projectMetrics.getHigh() >= high || //
			projectMetrics.getMedium() >= medium || //
			projectMetrics.getLow() >= low) {
		throw new SecurityGateRejectionException("Project did not pass the Security Gate");
	}
}
```

Expected behaviour:
The configured thresholds specify the number of issues for the given severity **before** the build fails. Only if the number of found issues is greater than the configured threshold - the build should fail.

**Comment by iabudiab** [comment]
Should be fixed in 0e3a844a546c8e43d4133dd872b6a8f5dfce7a51
